version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
  redis:
    image: redis
    ports:
      - "6379:6379"
